#!/bin/sh
# From - http://www.codingsteps.com/install-redis-2-6-on-amazon-ec2-linux-ami-or-centos/
# 
# redis - this script starts and stops the redis-sentinel daemon
#
# chkconfig:   - 85 15 
# description:  Redis sentinel is a system designed to help managing Redis instances.
# processname: redis-sentinel
# config:      /etc/redis-sentinel/sentinel.conf
# config:      /etc/sysconfig/sentinel.conf
# pidfile:     /var/run/redis-sentinel.pid
 
# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

sentinel="/usr/local/bin/redis-server"
prog=$(basename $sentinel)

REDIS_SENTINEL_CONF_FILE="/etc/redis-sentinel/sentinel.conf"

lockfile=/var/lock/subsys/redis-sentinel
 
start() {
    [ -x $sentinel ] || exit 5
    [ -f $REDIS_SENTINEL_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $sentinel $REDIS_CONF_FILE --sentinel
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
    echo -n $"$prog started succesfully "
}
 
stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
    echo -n $"$prog stopped succesfully "
}
 
restart() {
        echo -n "Restarting $prog ..."
        stop
        start
        echo -n $"$prog restarted succesfully "
}
 
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo "Usage $0 {start|stop|restart}"
                exit 2
esac